name: 'Tests' 
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  main:
    name: 'Tests'

    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Run tests
        uses: devcontainers/ci@v0.3
        with:
          runCmd: just ci
          push: never
